name: 'mdbook-full'
description: >
  Install mdbook with plugins
  svgbob, katex, linkcheck

branding:
  icon: upload-cloud
  color: green

# inputs:
  # pattern:
  #   description: 'file pattern to convert'
  #   required: true
  #   default: '**/*.md'

runs:
  using: "composite"
  steps:
    - name: install mdbook and plugins
      shell: bash
      run: |
        curl -LsSf https://github.com/drmingdrmer/mdbook-svgbob/releases/download/v0.1.2/mdbook-svgbob-v0.1.2-linux.zip -o mdbook-svgbob.zip
        unzip mdbook-svgbob.zip -d mdbook-svgbob
        echo "$PWD/mdbook-svgbob" >> $GITHUB_PATH

        curl -LsSf https://github.com/drmingdrmer/mdbook-katex/releases/download/v0.2.17/mdbook-katex-v0.2.17-linux.zip -o mdbook-katex.zip
        unzip mdbook-katex.zip -d mdbook-katex
        echo "$PWD/mdbook-katex" >> $GITHUB_PATH

        curl -LsSf https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v0.7.6/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip -o mdbook-linkcheck.zip
        unzip mdbook-linkcheck.zip -d mdbook-linkcheck
        chmod +x mdbook-linkcheck/mdbook-linkcheck
        echo "$PWD/mdbook-linkcheck" >> $GITHUB_PATH

        curl -LsSf https://github.com/rust-lang/mdBook/releases/download/v0.4.18/mdbook-v0.4.18-x86_64-unknown-linux-gnu.tar.gz -o mdbook.tar.gz
        mkdir mdbook
        tar xz  -f mdbook.tar.gz -C mdbook
        echo "$PWD/mdbook" >> $GITHUB_PATH
